hmcts/ccd-admin-web

- .travis.yml
- Dockerfile
- gulpfile.js
> Fix Codacy code issues

- infrastructure/saat.tfvars
> Update saat.tfvars to point to SIDAM

- infrastructure/saat.tfvars
> update SAAT SIDAM URL

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/RDM-2783
Prevent stale caches from breaking our builds
```
[ ] Yes
[ ] No
```
> RDM-2783: add 'yarn cache clean'

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2484 step 1
```
[ ] Yes
[x] No
```
> Remove keys that we tried to copy into the Azure vault

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2686
Implement a storage container in the shared storage account for CCD.
```
[ ] Yes
[x] No
```
> [PREVIEW] Add imports blob storage container

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2635
```
[ ] Yes
[x] No
```
> Infra: typo

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2484
Mostly done before.  Remove last references to Hashi vault.
```
[ ] Yes
[x] No
```
> [PREVIEW] Use Azure keys

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2484
```
[ ] Yes
[x] No
```
> [PREVIEW] Infra: remove Hashi vault

- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
- package.json
- src/main/domain/userrole.ts
- src/main/public/stylesheets/app.scss
- src/main/routes/create.user.profile.ts
- src/main/routes/delete.user.profile.ts
- src/main/routes/jurisdiction.ts
- src/main/routes/user.roles.ts
- src/main/service/create-user-role.ts
- src/main/service/get-user.roles.service.ts
- src/main/validators/validate.ts
- src/main/views/jurisdiction.html
- src/main/views/jurisdictions.html
- src/main/views/macros/formElements.html
- src/main/views/menu.html
- src/main/views/user-profiles/create-user-form.html
- src/main/views/user-roles.html
- src/main/views/user-roles/create-user-roles.html
- src/test/routes/user.roles.spec.ts
- src/test/service/create-user-role-service.spec.ts
- src/test/service/get.user.role.service.spec.ts
https://tools.hmcts.net/jira/browse/RDM-2707
https://tools.hmcts.net/jira/browse/RDM-1846
This PR is a combination of 2 stories Create user roles and displaying user roles in the results page, since they are tightly related , it made sense to combine them together and test then together too.
As a CMCA, I want to the ability to view a list of existing user roles in ccd for a selected/assigned jurisdiction
Fields:
Role 
Security Classification
```
[ ] Yes
[x] No
```
> Rdm 2707 - rdm-1846 - Create and Read User roles 

- infrastructure/sprod.tfvars
https://tools.hmcts.net/jira/browse/RDM-2635
Lock sprod while Performance Testing is happening.
```
[ ] Yes
[x] No
```
> [PREVIEW] Infra: keep sprod on per app ASP for Perf testing

- .dockerignore
- Dockerfile
- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDM-3046
```
[ ] Yes
[x] No
```
> Enable Docker build in pipeline

- infrastructure/prod.tfvars
> Update Demo Env with latest Master

- .travis.yml
https://tools.hmcts.net/jira/browse/RDM-3093
```
[ ] Yes
[x] No
```
> Drop Node 8.4 from Travis

- .dockerignore
- .snyk
- Dockerfile
- Jenkinsfile_CNP
- kubernetes/config.aat.yaml
- kubernetes/config.saat.yaml
- kubernetes/deployment.template.yaml
https://tools.hmcts.net/jira/browse/RDM-3223
```
[ ] Yes
[x] No
```
> Enable AKS

- .travis.yml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-3592
```
[ ] Yes
[ ] No
```
> Lock Terraform AzureRM provider to v1.19.0

- config/default.yaml
- src/main/routes/definitions.ts
- src/main/routes/userProfiles.ts
- src/main/util/render.ts
- src/main/validators/validateJurisdiction.ts
- src/main/views/definitions.html
- src/main/views/user-profiles.html
Attempt to fix duplication issue by changing URL property.
None.
Fix duplication in `src/main/routes/definitions.ts` and `src/main/routes/userProfiles.ts` by changing the "URL" property used in `definitions.ts` to the correct one, instead of using the User Profiles one as a dummy.
```
[ ] Yes
[x] No
```
> Fix Sonar duplication issue

- src/test/validators/validateJurisdiction.spec.ts
None.
Additional test to cover new code, flagged by Sonar.
```
[ ] Yes
[x] No
```
> Add test to cover validateJurisdiction validator

- src/test/routes/definitions.spec.ts
- src/test/routes/userProfiles.spec.ts
Add tests to increase new code coverage reported by Sonar.
None.
Attempt to get test coverage on new code up to the minimum 80% threshold.
```
[ ] Yes
[x] No
```
> Increase test coverage

- config/default.yaml
- src/main/routes/definitions.ts
- src/main/views/definitions.html
- src/test/routes/definitions.spec.ts
https://tools.hmcts.net/jira/browse/RDM-2928.
Implementation of the Definitions list screen for Case Admin Web.
```
[ ] Yes
[x] No
```
> RDM-2928: Draft Definitions list screen

- config/default.yaml
- config/mocha.yaml
- config/test.yaml
- infrastructure/main.tf
- infrastructure/variables.tf
- package.json
- src/main/app-insights/app-insights.spec.ts
- src/main/app-insights/app-insights.ts
- src/main/app.test.ts
- src/main/app.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-2618
https://tools.hmcts.net/jira/browse/RDM-3664
https://tools.hmcts.net/jira/browse/RDM-3722
1. Enabled App Insights
2. Allow single app insight usage
3. Use app insights in UK South
```
[ ] Yes
[ ] No
```
> [PREVIEW] Shared App Insight

- config/custom-environment-variables.yaml
- infrastructure/main.tf
RDM-3964
Add configs for import audits and whoami
```
[ ] Yes
[x] No
```
> RDM-3694 Add configs for import audits and whoami

- src/main/views/import-audits_inc.html
RDM-3762
Within the constraints of current look and feel, 
try to make 3rd column smaller
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-3762 PREVIEW

- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
- package.json
- src/main/domain/definition.ts
- src/main/routes/createDefinition.ts
- src/main/routes/updateDefinition.ts
- src/main/routes/updateUser.ts
- src/main/service/create-definition-service.ts
- src/main/views/definition/create-definition-form.html
- src/main/views/definitions.html
- src/test/routes/createDefinition.spec.ts
- src/test/routes/updateDefinition.spec.ts
- src/test/service/create-definition-service.spec.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-3015.
Initial version of Update Draft Definition functionality.
```
[ ] Yes
[x] No
```
> RDM-3015: Update Draft Definition

- .travis.yml
- Dockerfile
- package.json
https://tools.hmcts.net/jira/browse/RDM-3320
```
[ ] Yes
[x] No
```
> Set minimum yarn version

- package.json
- yarn.lock
> Bump snyk to v1.122.4

- infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
> Use SIDAM on SAAT for testing

- infrastructure/saat.tfvars
RDM-3960
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
> Use https and port 8443 for SIDAM on SAAT

- .dockerignore
- .gitignore
- Dockerfile
- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/CNP-1131
This PR leverages on layers re-use to reduce the the docker image build time in CI. However, this project using a specific branch of the Jenkins pipeline, **it will have an effect only if you use the latest version of the Jenkins library**.
> cnp-1131-acr-tasks

- infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
> Revert http on authentication URL

- yarn.lock
> Upgrade express and serve-favicon to eliminate fresh vulnerability

- src/main/app.ts
https://tools.hmcts.net/jira/browse/RDM-4210.
Temporary fix to restore display of error messages on the Import Definition page. Needs further investigation to extend error handler usage to other pages, if required.
```
[ ] Yes
[x] No
```
> RDM-4210: Fix routing on error handler

- infrastructure/saat.tfvars
> Update SAAT with Sidam

- infrastructure/saat.tfvars
Reverts hmcts/ccd-admin-web#184
> Revert "Update SAAT with Sidam"

- infrastructure/demo.tfvars
> switch idam_api_url and authentication_web_url

- infrastructure/saat.tfvars
> updating SIDAM values

- charts/ccd-admin-web/values.aat.template.yaml
- charts/ccd-admin-web/values.template.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
- src/main/app.test-admin-web-roles-authorized.ts
- src/main/app.ts
- src/main/public/stylesheets/app.scss
- src/main/routes/confirmDeleteItem.ts
- src/main/routes/createDefinition.ts
- src/main/routes/createUser.ts
- src/main/routes/home.ts
- src/main/routes/importDefinition.ts
- src/main/routes/jurisdiction.ts
- src/main/routes/logout.ts
- src/main/routes/updateDefinition.ts
- src/main/routes/updateUser.ts
- src/main/routes/userRoles.ts
- src/main/util/render.ts
- src/main/views/layout_template.html
- src/test/http-mocks/idam.ts
- src/test/routes/confirmDeleteItem.spec.ts
- src/test/routes/jurisdiction.spec.ts
- src/test/routes/logout.spec.ts
https://tools.hmcts.net/jira/browse/RDM-3381.
Show the current user's forename and surname on the right-hand side of the header, along with a link to sign out of the application.
```
[ ] Yes
[x] No
```
> RDM-3381: Display logged-in user and "Sign out" link

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-4846.
Remove redundant configuration from Terraform infrastructure config, to prevent unnecessary provision of Azure Blob Storage containers in each CNP environment.
```
[ ] Yes
[x] No
```
> [PREVIEW] RDM-4846: Remove redundant Azure Blob Storage config

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-5175
Upgrade Tomcat version to 9
```
[ ] Yes
[X] No
```
> change base module source for upgrage tomcat version

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-5175
fix the name for base config for module definition
```
[ ] Yes
[X] No
```
> fix name of base module def

- Dockerfile
- acb.tpl.yaml
https://tools.hmcts.net/jira/browse/RDM-5330?filter=-1
```
[ ] Yes
[x ] No
```
> RDM-5330-update ccd to use new docker registry url

- README.md
- config/default.yaml
- src/main/routes/createDefinition.ts
- src/main/routes/createUser.ts
- src/main/routes/importDefinition.ts
- src/main/routes/jurisdiction.ts
- src/main/routes/updateDefinition.ts
- src/main/routes/updateUser.ts
- src/main/routes/userRoles.ts
- src/main/util/render.ts
https://tools.hmcts.net/jira/browse/RDM-5351
Fixe for sanitize issue with json object.  `xss-filters.inHTMLData` internally calls Object.toString() which will return [object Object] by default.
```
[ ] Yes
[x ] No
```
> RDM-5351 - fixed sanitize issue with json object.

- charts/ccd-admin-web/Chart.yaml
- charts/ccd-admin-web/requirements.yaml
> bump up base chart version

- charts/ccd-admin-web/Chart.yaml
> bump up chart version

- charts/ccd-admin-web/values.yaml
> some fixes

- charts/ccd-admin-web/Chart.yaml
- charts/ccd-admin-web/requirements.yaml
> bump up idam pr

- .npmrc
- .travis.yml
- Dockerfile
- README.md
- gulpfile.js
- infrastructure/main.tf
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-3593
Update project to use node 12.x
```
[ ] Yes
[x] No
```
> RDM-3593 - Update to node 12.x

- Jenkinsfile_CNP
> RDM-7554 Remove the deprecated `enableDockerBuild()`

- charts/ccd-admin-web/Chart.yaml
- charts/ccd-admin-web/requirements.yaml
> RDM-7867-Update-base-chart

- package.json
- yarn.lock
AB#798
Added missing Properties Volume dependency. This module is used to incorporate the integration of the Azure key-vault flex volume to node properties
```
[ ] Yes
[x] No
```
> Added missing Properties Volume dependency

- server.js
AB#798
Added missing config for loading hmcts/properties-volume library. 
```
[ ] Yes
[x] No
```
> Loaded the properties-volume library

- package.json
- yarn.lock
fix security issue in dependency
> Force upgrade of assign-deep

- .github/renovate.json
- charts/ccd-admin-web/Chart.yaml
- charts/ccd-admin-web/requirements.yaml
> RDM-8784-Helm-Renovate

- config/default.yaml
- config/mocha.yaml
- config/test.yaml
> Remove default secrets

- Jenkinsfile_CNP
- bin/run-yarn-audit.sh
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-8990
Add yarn audit; fix vulnerabilities
```
[ ] Yes
[x] No
```
> RDM-8990 - Add yarn audit; fix vulnerabilities

- charts/ccd-admin-web/Chart.yaml
- charts/ccd-admin-web/values.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- src/main/app.ts
- src/main/routes/indexElasticsearch.ts
- src/main/service/elastic-index-service.ts
- src/main/views/elasticsearch.html
- src/main/views/menu.html
- src/test/routes/indexElasticsearch.spec.ts
- src/test/service/elastic-index-service.spec.ts
https://tools.hmcts.net/jira/browse/RDM-9262
New page to trigger Elasticsearch indexing in Definition Store
```
[ ] Yes
[x] No
```
> RDM-9262 - New page to trigger Elasticsearch indexing

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-5300
https://tools.hmcts.net/jira/browse/RDM-9438
```
[ ] Yes
[ ] No
```
> Rdm 5300 - Security Vulnerabilities on Admin-web repo

- src/main/server.ts
https://tools.hmcts.net/jira/browse/RDM-9731
Forced the client to use most latest secure protocol
```
[ ] Yes
[x] No
```
> RDM 9731: Force the client to use most latest secure protocol

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-10294
Fix All Recent CVEs in All CCD Apps
```
[ ] Yes
[X] No
```
> RDM-10294 Fix All Recent CVEs in All CCD Apps

- src/main/server.ts
https://tools.hmcts.net/jira/browse/RDM-9731
Forced the client to use most latest secure protocol
```
[ ] Yes
[x] No
```
> RDM 9731: Force the client to use latest secure protocol

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RDM-10583
```
[ ] Yes
[X] No
```
> Fix All Recent CVEs

- src/main/app-insights/app-insights.ts
https://tools.hmcts.net/jira/browse/RDM-11179
Page loading delay due to appinsights has been fixed
```
[ ] Yes
[x] No
```
> RDM-11179: Fix the page loading delay due to app insights

- package.json
- yarn.lock
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-11844
Change description
bump up dependencies to resolve CVEs
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
> bump up dependencies to resolve CVEs

- charts/ccd-admin-web/Chart.yaml
https://tools.hmcts.net/jira/browse/RDM-12175
Upgrade Base Chart Versions
```
[ ] Yes
[X] No
```
> RDM-12175 Upgrade Base Chart Versions

- Dockerfile
https://tools.hmcts.net/jira/browse/RDM-12088
Reset to default user after package update
```
[ ] Yes
[x] No
```
> RDM-12088: Reset to default user after package update

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CCD-1043
Fix Advisory - 1677 in CCD Admin web
```
[ ] Yes
[x] No
```
> CCD-1043 Fix Admin web CVE's

- Dockerfile
https://tools.hmcts.net/jira/browse/CCD-1649
fix for Fortify Issue 14640857 Dockerfile : 19
```
[ ] Yes
[ ] No
```
> fix for Fortify Issue 14640857 Dockerfile : 19

- package.json
- yarn.lock
Resolve CVE-2021-23406
```
[ ] Yes
[x] No
```
> CFTS-1029 Resolve CVE-2021-23406

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CCD-2658
CVE-2022-0536 in devDependencies
```
[ ] Yes
[x ] No
```
> CCD-2658: CVE-2022-0536

- charts/ccd-admin-web/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
> helm chart update

- src/test/java/build.gradle
https://tools.hmcts.net/jira/browse/CCD-3802
Update to fortify-client version
```
[ ] Yes
[ x] No
```
> CCD-3802 Update to fortify-client version

- src/main/service/manage-welsh-dictionary-service.ts
https://tools.hmcts.net/jira/browse/WLTS-55
Support quotes in the middle of strings and null values
```
[ ] Yes
[X] No
```
> WLTS-55 Support quotes in the middle of strings and null values

- src/test/service/delete-definition-service.spec.ts
> Ignore the intermittently failing tests

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/CCD-4336
updated package versions
```
[ ] Yes
[X] No
```
> CCD-4336: updated package versions

- package.json
- src/test/routes/deleteDefinition.spec.ts
- src/test/routes/deleteUser.spec.ts
- src/test/routes/importDefinition.spec.ts
- src/test/routes/oauth2redirect.spec.ts
- yarn.lock
> Partial test fixes for Node 18

- package.json
- yarn.lock
> Add js-yaml

- .dockerignore
- Dockerfile
NA
enabled corepack
```
[ ] Yes
[X] No
```
> Test update corepack

- package.json
- src/main/service/import-service.ts
- src/main/views/importDefinition.html
- src/test/service/import-service.spec.ts
Reverts hmcts/ccd-admin-web#642
https://tools.hmcts.net/jira/browse/CME-264
> Revert "CME-264: add indexing checkboxes "
